# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    #image: postgres
    build:
      context: ./postgres
    image: postgres-custom:1.0
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080